read -p "Enter 1st digit= " d1
read -p "Enter 2nd digit= " d2
read -p "Enter 3rd digit= " d3
read -p "Enter 4th digit= " d4
read -p "Enter 5th digit= " d5
read -p "Enter 6th digit= " d6
read -p "Enter 7th digit= " d7
read -p "Enter 8th digit= " d8
read -p "Enter 9th digit= " d9
sum=$(( d1 + d2 + d3 + d4 + d5 + d6 + d7 + d8 + d9 ))
echo "sum= $sum"
